dataset: samsum	No info from HuggingFace
dataset: samsum,samsum	splits: train: 14732 rows, test: 819 rows, val: 818 rows
dataset: samsum,samsum	split: train	columns: id, dialogue, summary
***ERROR***
model: None
data: H:samsum
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7efbe19ae300>)
