dataset: daily_dialog	No info from HuggingFace
dataset: daily_dialog	splits: train: 11118 rows, test: 1000 rows, val: 1000 rows
dataset: daily_dialog	split: train	columns: dialog, act, emotion
***ERROR***
model: None
data: H:daily_dialog
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7fd2361fe140>)
